#!/bin/bash
set -e

# ==========================================
# CONFIGURATION
# ==========================================
if [ -z "$ISSUE_NUMBER" ]; then
  echo "❌ Error: No Issue Number provided (env var ISSUE_NUMBER missing)."
  exit 1
fi

echo "🤖 [RALPH] Waking up. Target: Issue #$ISSUE_NUMBER"

# Ensure we are in the root of the repo
cd "$(git rev-parse --show-toplevel)"

# ==========================================
# 1. SETUP: Configure Claude (Headless)
# ==========================================
echo "🔧 [RALPH] Configuring Claude Code..."
mkdir -p ~/.config/claude-code

# Use the GitHub MCP server (via Docker) to give Claude native access to issues
cat <<EOF > ~/.config/claude-code/config.json
{
  "mcpServers": {
    "github": {
      "command": "docker",
      "args": [
        "run", 
        "-i", 
        "--rm", 
        "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", 
        "ghcr.io/github/github-mcp-server:latest"
      ],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "$PAT_TOKEN"
      }
    }
  }
}
EOF

# ==========================================
# 2. PLANNING PHASE
# ==========================================
echo "📋 [RALPH] Analyzing Issue..."

# --dangerously-skip-permissions is critical for CI/CD so it doesn't ask for "Y/N"
# -p runs in print (non-interactive) mode

PROMPT_PLAN="I am an autonomous agent working on GitHub Issue #$ISSUE_NUMBER.
1. Read the issue details.
2. Explore the codebase to understand the context.
3. Create a file named 'PLAN.md' with a step-by-step checklist to solve the issue.
4. Create a file named 'PROGRESS.md' to track status.
Do NOT write code yet. Just plan."

claude -p "$PROMPT_PLAN" --dangerously-skip-permissions

# ==========================================
# 3. CODING LOOP (Max 5 iterations)
# ==========================================
MAX_LOOPS=5
CURRENT_LOOP=1

while [ $CURRENT_LOOP -le $MAX_LOOPS ]; do
    echo "🔨 [RALPH] Coding Loop $CURRENT_LOOP / $MAX_LOOPS"
    
    PROMPT_LOOP="Read 'PLAN.md' and 'PROGRESS.md'.
    Pick the next unchecked item. Implement it.
    Run local tests (npm test / pytest) to verify.
    Update 'PLAN.md' and 'PROGRESS.md'.
    
    If the plan is fully done and tests pass, output exactly: 'RALPH_COMPLETE'.
    Otherwise, output 'CONTINUING'."
    
    OUTPUT=$(claude -p "$PROMPT_LOOP" --dangerously-skip-permissions)
    echo "$OUTPUT"
    
    if [[ "$OUTPUT" == *"RALPH_COMPLETE"* ]]; then
        echo "✅ [RALPH] Tasks Completed."
        break
    fi
    ((CURRENT_LOOP++))
done

# ==========================================
# 4. FRESH REVIEW & PR
# ==========================================
echo "🧐 [RALPH] Reviewing work..."

REVIEW_RESULT=$(claude -p "Act as a Senior Reviewer. Run 'git diff'. Compare against Issue #$ISSUE_NUMBER. If code is good, output 'PASS'. If bad, output 'FAIL'." --dangerously-skip-permissions)

if [[ "$REVIEW_RESULT" == *"PASS"* ]]; then
    echo "🚀 Review Passed. Creating PR..."
    
    BRANCH_NAME="fix/issue-$ISSUE_NUMBER-auto-$(date +%s)"
    
    # Git Configuration
    git config --global user.email "ralph-bot@users.noreply.github.com"
    git config --global user.name "Ralph Bot"
    
    # Create Branch & Push
    git checkout -b "$BRANCH_NAME"
    git add .
    git commit -m "Fix: Automated resolution for Issue #$ISSUE_NUMBER"
    git push origin "$BRANCH_NAME"
    
    # Open PR via Claude
    claude -p "Create a Pull Request for branch '$BRANCH_NAME' targeting 'main'.
    Title: 'Fix: Issue #$ISSUE_NUMBER (Ralph Agent)'
    Body: 'Closes #$ISSUE_NUMBER. Automatically generated by Ralph.'" --dangerously-skip-permissions
    
    echo "🎉 [RALPH] PR Created."
else
    echo "❌ Review Failed."
    exit 1
fi
